spring.application.name=proyecto_final

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/bd_galeria_comercial
spring.datasource.username=root
spring.datasource.password=password
